name: Check that there are no large binary files

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  large-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # We analyze Git history

      - name: Check for large files
        uses: Amadevus/pwsh-script@v2
        env:
          BASE_REF: ${{ github.base_ref }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          script: |
            $global:ProgressPreference = 'SilentlyContinue'
            Set-StrictMode -Version 3.0

            Install-Module PowerGit -Force -ErrorAction Stop
            Install-Module PSGitHub -Force -ErrorAction Stop

            $PSDefaultParameterValues['*:GitHub*'] = ConvertTo-SecureString -String $env:GITHUB_TOKEN -AsPlainText -Force

            ./src/scripts/check-large-files.ps1 -BaseRef $env:BASE_REF -PullRequestNumber $github.event.pull_request.number
