name: Check all links between pages are valid

on: push

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        env:
          FORCE_COLOR: 3
        with:
          use-quiet-mode: 'yes'
          use-verbose-mode: 'yes'
          folder-path: ./content
          # Don't check external links, because those could go down without a change on our side,
          # making builds non-reproducable.
          # TODO: Add a check for external links in a cronjob that could report to Slack.
          config-file: .github/workflows/link-check-internal.json
